- debian/build-sa-efi-images
- debian/endless-uefi-grub.cfg
- debian/rules
https://phabricator.endlessm.com/T12000
> build-sa-efi-images: Move configuration script to a stand-alone file

- debian/build-sa-efi-images
https://phabricator.endlessm.com/T12093
> build-sa-efi-images: Add more pre-loaded modules

- debian/build-sa-efi-images
https://phabricator.endlessm.com/T12093
> build-sa-efi-images: s/bootx64.efi/grubx64.efi/

- grub-core/commands/blscfg.c
https://phabricator.endlessm.com/T12512
> blscfg: Introduce 'kparams' env to add custom bootargs

- debian/build-sa-efi-images
- debian/endless-uefi-grub.cfg
https://phabricator.endlessm.com/T12512
> endless-uefi-grub.cfg: Support combined live + installer boot

- grub-core/commands/search.c
https://phabricator.endlessm.com/T13311
> search: Do not try to autoload fs modules when secure booted

- debian/endless-uefi-grub.cfg
https://phabricator.endlessm.com/T13375
> endless-uefi-grub.cfg: Disable hibernation when booted from an image

- grub-core/commands/hexdump.c
https://phabricator.endlessm.com/T13301
> hexdump: Add export to variable

- debian/rules
https://phabricator.endlessm.com/T13374
> grubx64: Move to $ESP/endless/ directory

- grub-core/commands/blscfg.c
https://phabricator.endlessm.com/T13279
> blscfg: Introduce savedefault command

- grub-core/commands/probe.c
- grub-core/partmap/msdos.c
- include/grub/partition.h
https://phabricator.endlessm.com/T13592
> probe: Add a 'bootable' option

- grub-core/fs/fat.c
https://phabricator.endlessm.com/T13702
> exfat: Read the contiguous flag from the correct extension

- debian/endless-uefi-grub.cfg
https://phabricator.endlessm.com/T13557
> T13557: fix grub config to support ISO booting

- debian/endless-uefi-grub.cfg
https://phabricator.endlessm.com/T14961
> grub: s/live/image/

- debian/endless-uefi-grub.cfg
https://phabricator.endlessm.com/T13560
> ISO: Enable booting from a squashfs image

- debian/build-sa-efi-images
https://phabricator.endlessm.com/T15532
> build-sa-efi-images: Pre-load squash4 module

- grub-core/commands/blscfg.c
https://phabricator.endlessm.com/T13632
> blscfg: Show only one entry for Endless

- grub-core/commands/blscfg.c
https://phabricator.endlessm.com/T15448
> blscfg: Add initramfs-append to the initrd command line if it exists

- grub-core/commands/blscfg.c
https://phabricator.endlessm.com/T15448
> blscfg: Workaround compiler bug

- grub-core/fs/squash4.c
https://phabricator.endlessm.com/T15588
> squash4: fix handling of fragments and sparse files

- debian/build-sa-images
- debian/rules
https://phabricator.endlessm.com/T13334
> build-sa-images: Build standalone images also for BIOS

- debian/control
https://phabricator.endlessm.com/T13334
> control: Add dependency on util-linux

- debian/conf/grub.cfg
https://phabricator.endlessm.com/T14545
> grub.cfg: Do not list Windows when chainloaded from ntldr

- debian/build-sa-efi-images
Signed-off-by: Carlo Caione <carlo@endlessm.com>
> build-sa-efi-images: Ship ls module for debugging

- debian/conf/grub.cfg
https://phabricator.endlessm.com/T18551
> grub.cfg: Export grubenv to be seen by submenus

- util/grub-mkconfig.in
https://phabricator.endlessm.com/T19614
> grub-mkconfig: Do not allow grub.conf change on ostree systems

- debian/control
- debian/grub-efi-amd64-image.install.in
- debian/grub-efi-ia32-image.install.in
- debian/rules
https://phabricator.endlessm.com/T14870
> T14870 debian

- debian/changelog
https://phabricator.endlessm.com/T22742
> Add changelog entry explaining current status of this package
