grub-core/fs/fat.c

https://phabricator.endlessm.com/T13010

FAT/exFAT: Fix wrong size detection for files > 4GB

---

grub-core/loader/efi/chainloader.c

At present, you get output like this printed to the console when you
chainload another EFI binary (such as the Windows bootloader):
/EndEntire
file path: /ACPI(...)/.../.../File(BOOTMGFW.EFI)/EndEntire
This must have been for debugging at some point, but is confusing to end users. There
are similar calls to grub_efi_print_device_path() in efi/efidisk.c
guarded by DEBUG_NAMES, so let's guard these the same way.
https://phabricator.endlessm.com/T13258

efi/chainloader: don't print device path to console

---

debian/control

The grub-efi-amd64-image-signed package will provide grubx64.efi signed
by the Endless secure boot key. The file lives at the same spot, so the
packages must conflict with each other.
https://phabricator.endlessm.com/T12944

Make grub-efi-amd64-image conflict with signed version

---

grub-core/loader/i386/linux.c

If we're running under Secure Boot, the `linux` command tries to hand
the job of to `linuxefi`, which requires a valid signature. If that
fails, lets have `linux` fail as well instead of loading an unsigned
kernel.
https://phabricator.endlessm.com/T13811

Do not load unsigned kernels under EFI Secure Boot

---

grub-core/loader/efi/chainloader.c
include/grub/efi/api.h

Here's the output when I try to chainload 1MiB of `/dev/random` from the UEFI shell in VirtualBox:
And in GRUB with this patch (minus the URL bit):
Error `3` is `UNSUPPORTED`, so this seems to work…
https://phabricator.endlessm.com/T14019

efi/chainloader: add debug output on error

---

grub-core/commands/search.c
grub-core/commands/search_wrap.c
include/grub/search.h

Currently when you search for a file, if no result is found it prints
an error message.
That's not ideal when the file is optional, so add a --quiet arg
to silence this.
https://phabricator.endlessm.com/T14231

search: add optional --quiet parameter

---

debian/endless-uefi-grub.cfg

Otherwise this prints out an error message when the file can't be
found (e.g. on single-OS setups)
https://phabricator.endlessm.com/T14231

UEFI config: make search quiet

---

debian/build-sa-efi-images
debian/endless-uefi-grub.cfg

This is a regression in 559fa10 which I missed in review. Previously we
used `search.file`, which takes purely positional parameters. To support
--quiet we switched to `search --file`, a wrapper command which takes named
parameters (except for a single positional parameter -- in this case, the
filename to search for).
As a result, rather than initializing $eoslive, the partition ID was
printed to the console, and then we fell through to the full-installation
path.
I have reordered the parameters here to match the later call to `search
... --fs-type`. The remaining difference is the trailing comma on the hint,
which is significant.
https://phabricator.endlessm.com/T14231

Fix search --file syntax for image-boots

---

grub-core/loader/i386/linux.c

Fixes 7bdcf6d4b16a61bfa8a3b5e2a433956abcad09aa
For our converted systems we use the "linux" command and expect
it to dynamically redirect to linuxefi/initrdefi for secure boot
systems. But for this to work we have to allow the module to load.
https://phabricator.endlessm.com/T14258

linux: allow module to register when booting securely

---

debian/build-sa-efi-images
debian/rules

Remove the redundant mkdir from the rules file
(build-sa-efi-images does this).
Adjust script invocation to allow us to output a file named bootia32.efi
in the standard boot directory.
This adds support for booting UEFI-32 in unsecure mode.
https://phabricator.endlessm.com/T13970

Build bootia32.efi for UEFI-32 unsecure boot

---

Makefile.util.def
grub-core/Makefile.core.def

This is not of interest to Endless, and it is causing us some problems.
When searching for endless.img during boot, this fs module is reading
the last sector of available block devices.
We have now seen 2 cases where buggy UEFI firmware provides the
bad last sector number, causing very long delays during boot while
those sectors are attempted to be read.
Avoid this problem by disabling cbfs.
https://phabricator.endlessm.com/T14713

Disable cbfs module

---

debian/conf/grub.cfg

When loaded via eosldr, the following error is shown
Error: file `/grubenv' not found.
Press any key to continue...
(After pressing the Any Key, the system boot correctly, without a menu
from GRUB.) This is because $grubroot is only defined when eosldr is not
found.
We only want 'savedefault' to have any effect when we've shown a menu.
The correct conditions for that are ! $is_live && $eosimage && ! -f
($eosimage)/eosldr -- exactly the conditions under which $grubroot is
defined. So, make this explicit: define a variable for the path to the
'grubenv' file, and use this as the sole condition for savedefault to
have any effect.
https://phabricator.endlessm.com/T14545

conf: avoid "file '/grubenv' not found" under eosldr

---

debian/conf/grub_embedded_image.cfg

I have not tested this fix yet with the BIOS standalone image, but surely it should work the same? Famous last words.
https://phabricator.endlessm.com/T18758

Fix mashing ESC on EFI systems while image-booting

---

Makefile.util.def

We do not want to build this module, see 24f83f7 for rationale.
At autogen.sh time, po/POTFILES.in is generated by listing source files
in the source tree. When run from a git checkout, this includes cbfs.c.
po/POTFILES.in is included in the source tarball generated by make dist,
but cbfs.c was previously not included. This led to `make distcheck`
failing when it runs `make dist` on the re-unpacked tarball.
I cannot explain why this did not fail before. Could it be that an
Automake upgrade has changed the behaviour of `make distcheck`?
Of course, cbfs.c doesn't have any strings marked for translation
anyway...
https://phabricator.endlessm.com/T18922

Include cbfs.c in dist tarball

---

debian/build-sa-efi-images

This is used on the "Windows is hibernated" path. Without this, users
see the following:
Press ENTER to continue ...
error: file `/endless/grub/x86_64-efi/read.mod' not found.
Press any key to continue...
https://phabricator.endlessm.com/T13600

build-sa-efi-images: ship 'read' module

---

debian/build-sa-efi-images
debian/conf/grub.cfg

These patches address three related issues on dual-boot systems, in descending order of priority:
* https://phabricator.endlessm.com/T18551 - use `C:\endless\grub\grubenv` (fixes a regression in 3.3.6 which affects all new dual-boot installations)
* https://phabricator.endlessm.com/T20513 - add `hiberfil.sys` check on eosldr path (fixes a regression in 3.2.0, affects some but not all new dual-boot installations on BIOS machines)
* https://phabricator.endlessm.com/T20509 - use `file --is-hibernated-hiberfil` (no user-visible change, but will allow us to drop a downstream GRUB patch)
Merging all three together will reduce the number of times we have to test {dual boot, standalone} × {hibernated, not hibernated} × {BIOS, EFI}, but we could take any prefix

Use C:\...\grubenv; check hiberfil on eosldr; use file not hexdump

---

debian/rules

This package is currently failing on OBS with the error:
dh_install: Requested unknown package grub-efi-amd64-image-bin via
-p/--package, expected one of: ...
The problem (not reproducible locally) seems that we are passing to
dh_install a package name that is not defined in the control file
(grub-efi-amd64-image-bin).
Since we do not actually need any *-bin or *-dbg derivative package for
grub-efi-amd64-image and grub-efi-ia32-image, we just define a new rule
for dh_install filtering only on those two packages.
Signed-off-by: Carlo Caione <carlo@endlessm.com>

rules: Fix OBS dh_install error

---

grub-core/kern/i386/tsc.c

On efi systems, make pmtimer based tsc calibration the default over the
pit. This prevents Grub from hanging on Intel SoC systems that power gate
the pit.
Signed-off-by: David E. Box <david.e.box@linux.intel.com>
Reviewed-by: Daniel Kiper <daniel.kiper@oracle.com>
Origin: upstream, https://git.savannah.gnu.org/cgit/grub.git/commit/?id=446794de8da4329ea532cbee4ca877bcafd0e534
Bug-Debian: https://bugs.debian.org/883193
Last-Update: 2017-12-01
Patch-Name: tsc_efi_default_to_pmtimer.patch
Cherry-picked from https://salsa.debian.org/grub-team/grub/commit/edda6b09c43ecbd0f7735e0a78a5ea94ac5fda66.patch
https://phabricator.endlessm.com/T23172

tsc: Change default tsc calibration method to pmtimer on EFI systems

---

INSTALL
Makefile.am
Makefile.util.def
configure.ac

freetype-config was dropped completely in favor of using pkg-config instead.
https://phabricator.endlessm.com/T24680

Fix building with new libfreetype6-dev

---

grub-core/efiemu/i386/loadcore64.c
grub-core/fs/btrfs.c
grub-core/kern/x86_64/dl.c
grub-core/script/yylex.l
include/grub/efiemu/runtime.h
include/grub/partition.h
tests/uhci_test.in
tests/util/grub-shell.in
util/grub-mkimagexx.c
util/grub-module-verifier.c

The rebased of our distro on Debian Buster broke the grub build. Luckily the failures were all already sorted upstream, so this PR is a backport of a few upstream patches that address them.
https://phabricator.endlessm.com/T26580

Fix build after Debian Buster distro rebase.

---

grub-core/fs/ext2.c
tests/ext234_test.in
tests/util/grub-fs-tester.in

On such a filesystem, inodes may have EXT4_ENCRYPT_FLAG set.
For a regular file, this means its contents are encrypted; for a
directory, this means the filenames in its directory entries are
encrypted; and for a symlink, this means its target is encrypted.  Since
GRUB cannot decrypt encrypted contents or filenames, just issue an error
if it would need to do so.  This is sufficient to allow unencrypted boot
files to co-exist with encrypted files elsewhere on the filesystem.
(Note that encrypted regular files and symlinks will not normally be
encountered outside an encrypted directory; however, it's possible via
hard links, so they still need to be handled.)
Tested by booting from an ext4 /boot partition on which I had run
'tune2fs -O encrypt'.  I also verified that the expected error …

Allow GRUB to mount ext2/3/4 filesystems that have the encryption feature

---

grub-core/fs/minix.c

ext2 (and ext3, ext4) filesystems write the number of free inodes to
location 0x410.
On a minix filesystem, that same location is used for the minix superblock
magic number.
If the number of free inodes on an ext2 filesystem is equal to any
of the four minix superblock magic values plus any multiple of 65536,
grub's minix filesystem code will probe it as a minix filesystem.
In the case of an OS using ext2 as the root filesystem, since there will
ordinarily be some amount of file creation and deletion on every bootup,
it effectively means that this situation has a 1:16384 chance of being hit
on every reboot.
This will cause grub's filesystem probing code to mistakenly identify an
ext2 filesystem as minix. This can be seen by e.g. "search --label"
incorrectly indicating that no such ext2 …

minix: avoid mistakenly probing ext2 filesystems

---

grub-core/commands/file.c

commit f1957dc8a3347278a095bc8f44197662559a8ba3 added two entries to the
options array, but only 1 entry to the enum. This resulted in everything
after the insertion point being off by one.
This broke at least the 'file --is-hibernated-hiberfil' command.
Bring the two back in sync by splitting the RISCV enum entry into two,
as is done for other architectures.

commands/file: Fix array/enum desync

---

grub-core/kern/main.c

WARNING FOR REBASER: This patch *MUST* be dropped when Debian drops their
downstream lockdown and secure boot/shim validation patches!!!
This disables the verifier infrastructure, which is currently the upstream
way to do secure boot verification of kernel images, as well as the way
upstream prevents loading of unsigned modules when secure boot is active.
Debian currently has their own patches that do these things, so we're
stuck with those. With debian's patches at time of this writing, the
shim_lock verifier is intentionally broken, so the verifier framework will
deny booting anything while secure boot is active.
We disable verifiers, and Debian's lockdown and shim_lock machinery works.
At some point in the future (grub 2.06?) Debian will likely move to the
upstream validation methods, …

[ENDLESS] break verifiers to stop boot failures READ LOG WHEN REBASING

---

debian/sbat.endless.csv.in

Fix package versions in our SBAT file
Because we have Jenkins generate the package for us, @UPSTREAM_VERSION@
is not quite the actual version for GRUB upstream, but the portion of
the version string corresponding to the main code branch
(2.04+dev245.7421863), so we should instead spell-out the real upstream
version (2.04).
For our own downstream version, we should use @UPSTREAM_VERSION@ instead
of @DEB_VERSION@, so we leave out the packaging version and build
counter, as we do for shim's SBAT section.
https://phabricator.endlessm.com/T31888

fixup! SBAT: Add endless SBAT

---

debian/build-sa-efi-images
debian/rules

The grub EFI image we actually put in the ESP is built with our own
`build-sa-efi-images` script, not the `build-efi-images` script provided
by debian. While debian's script was updated to include the SBAT data in
the images, ours was not.
Update `build-sa-efi-images` to require an SBAT CSV file argument and
pass it in the `--sbat` option to `grub-mkstandalone`. The CSV
templating is not pretty but was copied from the `build-efi-images`
recipe for consistency.
https://phabricator.endlessm.com/T32500

Include SBAT data in standalone EFI images
